spring:
  application:
    name: gray-server
  profiles:
    active: dev
server:
  port: 20202
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 8
    lease-expiration-duration-in-seconds: 20
gray:
  mq:
    path: config/dev/mq.properties
  mysql:
    path: config/dev/mysql.properties