spring:
  application:
    name: gray-server
  profiles:
    active: dev
server:
  port: 20202
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
gray:
  server :
    name : ${spring.application.name}
  mq:
    path: config/dev/mq.properties
  mysql:
    path: config/dev/mysql.properties
  redis:
    path: config/dev/redis.properties