spring:
  application:
    name: service-a
  profiles:
    active: test
server:
  port: 20103
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    instanceId: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 8
    lease-expiration-duration-in-seconds: 20
gray:
  client:
    pull-inteval : 20000
    server-name: gray-server #灰度服务端的service name
  instance:
    enroll: true #是否在启动后自动注册成灰度实例
    enroll-dealy : 20000 #注册成灰度实例的延时时长
  mq:
    path: config/dev/mq.properties